version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/set-me-on-fire
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Generate test build
          command: npm run build
